apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: shopmicro
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      logging:
        loglevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlp/tempo:
        endpoint: "tempo:14250"
        insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
