apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: shopmicro
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 14250

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces