apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shopmicro-frontend:latest
        imagePullPolicy: Never
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend:3001"
        - name: OTEL_SERVICE_NAME
          value: "shopmicro-frontend"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopmicro
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
