apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.0.0
        ports:
        - containerPort: 3200
        - containerPort: 14250
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: shopmicro
spec:
  selector:
    app: tempo
  ports:
  - name: http
    port: 3200
    targetPort: 3200
  - name: grpc
    port: 14250
    targetPort: 14250
