apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.0.0
        args: ["-config.file=/etc/tempo/tempo.yaml"]
        ports:
        - containerPort: 3200   # http
        - containerPort: 14250  # grpc
        volumeMounts:
        - name: config
          mountPath: /etc/tempo
      volumes:
      - name: config
        configMap:
          name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: shopmicro
spec:
  selector:
    app: tempo
  ports:
  - name: http
    port: 3200
    targetPort: 3200
  - name: grpc
    port: 14250
    targetPort: 14250